refl: 'SR'
http-specs: ''
http-chips: ''
file-specs: ''
file-chips: ''
file-root: ''
file-specs:
  blue:
    - 'LC08_{refl}B2'
    - 'LE07_{refl}B1'
    - 'LT05_{refl}B1'
    - 'LT04_{refl}B1'
  green:
    - 'LC08_{refl}B3'
    - 'LE07_{refl}B2'
    - 'LT05_{refl}B2'
    - 'LT04_{refl}B2'
  red:
    - 'LC08_{refl}B4'
    - 'LE07_{refl}B3'
    - 'LT05_{refl}B3'
    - 'LT04_{refl}B3'
  nir:
    - 'LC08_{refl}B5'
    - 'LE07_{refl}B4'
    - 'LT05_{refl}B4'
    - 'LT04_{refl}B4'
  swir1:
    - 'LC08_{refl}B6'
    - 'LE07_{refl}B5'
    - 'LT05_{refl}B5'
    - 'LT04_{refl}B5'
  swir2:
    - 'LC08_{refl}B7'
    - 'LE07_{refl}B7'
    - 'LT05_{refl}B7'
    - 'LT04_{refl}B7'
  thermal:
    - 'LC08_BTB10'
    - 'LE07_BTB6'
    - 'LT05_BTB6'
    - 'LT04_BTB6'
  quality:
    - 'LC08_PIXELQA'
    - 'LE07_PIXELQA'
    - 'LT05_PIXELQA'
    - 'LT04_PIXELQA'

conus-extent:
  xmin: -2565585
  ymax: 3314805
  xmax: 2384415
  ymin: 14805
alaska-extent:
  xmin: -851715
  ymax: 2474325
  xmax: 1698285
  ymin: 374325
hawaii-extent:
  xmin: -444345
  ymax: 2168895
  xmax: 305655
  ymin: 1718895

conus-tileaff: [-2565585, 150000, 0 , 3314805, 0, -150000]
conus-chipaff: [-2565585, 3000, 0 , 3314805, 0, -3000]
