http-specs: ''
http-chips: ''
file-specs: ''
file-chips: ''
file-root: ''
file-specs:
  blue:
    - 'LC08_SRB2'
    - 'LE07_SRB1'
    - 'LT05_SRB1'
    - 'LT04_SRB1'
  green:
    - 'LC08_SRB3'
    - 'LE07_SRB2'
    - 'LT05_SRB2'
    - 'LT04_SRB2'
  red:
    - 'LC08_SRB4'
    - 'LE07_SRB3'
    - 'LT05_SRB3'
    - 'LT04_SRB3'
  nir:
    - 'LC08_SRB5'
    - 'LE07_SRB4'
    - 'LT05_SRB4'
    - 'LT04_SRB4'
  swir1:
    - 'LC08_SRB6'
    - 'LE07_SRB5'
    - 'LT05_SRB5'
    - 'LT04_SRB5'
  swir2:
    - 'LC08_SRB7'
    - 'LE07_SRB7'
    - 'LT05_SRB7'
    - 'LT04_SRB7'
  thermal:
    - 'LC08_BTB10'
    - 'LE07_BTB6'
    - 'LT05_BTB6'
    - 'LT04_BTB6'
  quality:
    - 'LC08_PIXELQA'
    - 'LE07_PIXELQA'
    - 'LT05_PIXELQA'
    - 'LT04_PIXELQA'
